# Generated by Django 4.2 on 2024-05-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_profile_pictures.png', upload_to='profile_pictures'),
        ),
    ]
