# Generated by Django 4.0 on 2024-04-13 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
