# Generated by Django 4.0 on 2024-05-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_picture',
        ),
    ]
